# Generated by Django 4.2.8 on 2024-01-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=254)),
                ('view_genre', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('non-fiction', 'Non-Fiction'), ('fiction', 'fiction'), ('childrens', 'Childrens')], default='Non-Fiction', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=254, null=True)),
                ('author', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('link', models.CharField(blank=True, max_length=254, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('first_published', models.PositiveIntegerField(blank=True, null=True)),
                ('this_publication_date', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=50)),
                ('description', models.TextField()),
                ('language', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre')),
            ],
        ),
    ]
