# Generated by Django 4.2.8 on 2024-02-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non-fiction', 'Non-Fiction'), ('fiction', 'Fiction'), ('childrens', 'Childrens')], default='Non-Fiction', max_length=50),
        ),
    ]
