# Generated by Django 4.2.8 on 2024-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('non-fiction', 'Non-Fiction'), ('fiction', 'Fiction'), ('childrens', 'Childrens')], default='Category', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='Condition', max_length=50),
        ),
    ]
