# Generated by Django 4.2.8 on 2024-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscribers_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
