# Generated by Django 4.2.8 on 2024-02-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletters_delete_mailmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscribers_name',
        ),
    ]
